chore: bound the parallelism
cdklabs/cdk-assets pull request #162
Opened 2024-11-05 13:45 UTC by rix0rrr

Add the linter rule that checks for bounded parallelism, and mark the 2 locations that do `Promise.all` as bounded.

2024-11-05 13:48 UTC, mrgrain commented on lib/publishing.ts
> +      const limit = pLimit(20);
Do we need/want to be this restrictive?

2024-11-05 13:49 UTC, mrgrain requested changes
Sicne this is a public facing package, can you phrase the title and description more customer focused. It will show up in the changelog (or not get released if we change it back to a chore).

2024-11-05 13:56 UTC, rix0rrr commented
Should have been a chore, thanks

2024-11-05 15:27 UTC, mrgrain approved these changes

2024-11-05 15:30 UTC, merged

2024-11-06 11:19 UTC, aws-cdk-automation commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|v2-main|[<img src="https://img.shields.io/github/pulls/detail/state/cdklabs/cdk-assets/166">](https://github.com/cdklabs/cdk-assets/pull/166)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport) and see the [Github Action logs](https://github.com/cdklabs/cdk-assets/actions/runs/11702508912) for details

<!--- Backport version: 9.5.1 -->